/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cmodules;

public class Entity {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Entity(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Entity obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      mainJNI.delete_Entity(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setStatut(int arg0) {
    mainJNI.Entity_setStatut(swigCPtr, arg0);
  }

  public int getStatut() {
    return mainJNI.Entity_getStatut(swigCPtr);
  }

  public void setPos(int arg0, int arg1) {
    mainJNI.Entity_setPos(swigCPtr, arg0, arg1);
  }

  public int getPosX() {
    return mainJNI.Entity_getPosX(swigCPtr);
  }

  public int getPosY() {
    return mainJNI.Entity_getPosY(swigCPtr);
  }

  public void setPosX(int posX) {
    mainJNI.set_Entity_posX(swigCPtr, posX);
  }

  public void setPosY(int posY) {
    mainJNI.set_Entity_posY(swigCPtr, posY);
  }

  public Entity() {
    this(mainJNI.new_Entity(), true);
  }

}
