/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cmodules;

public class example {
  public static int gcd(int x, int y) {
    return exampleJNI.gcd(x, y);
  }

  public static void setFoo(double value) {
    exampleJNI.set_Foo(value);
  }

  public static double getFoo() {
    return exampleJNI.get_Foo();
  }

}
