/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cmodules;

public class GlobalStatut {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected GlobalStatut(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GlobalStatut obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      mainJNI.delete_GlobalStatut(swigCPtr);
    }
    swigCPtr = 0;
  }

  public GlobalStatut() {
    this(mainJNI.new_GlobalStatut(), true);
  }

  public void setStatut(int Statut) {
    mainJNI.set_GlobalStatut_Statut(swigCPtr, Statut);
  }

  public int getStatut() {
    return mainJNI.get_GlobalStatut_Statut(swigCPtr);
  }

  public void askEnd() {
    mainJNI.GlobalStatut_askEnd(swigCPtr);
  }

  public void setEndAsked(int endAsked) {
    mainJNI.set_GlobalStatut_endAsked(swigCPtr, endAsked);
  }

  public int getEndAsked() {
    return mainJNI.get_GlobalStatut_endAsked(swigCPtr);
  }

  public int endIsAsked() {
    return mainJNI.GlobalStatut_endIsAsked(swigCPtr);
  }

  public void dataUpdated() {
    mainJNI.GlobalStatut_dataUpdated(swigCPtr);
  }

  public int isNewDataAvailable() {
    return mainJNI.GlobalStatut_isNewDataAvailable(swigCPtr);
  }

  public void consumeData() {
    mainJNI.GlobalStatut_consumeData(swigCPtr);
  }

  public int isDataConsumed() {
    return mainJNI.GlobalStatut_isDataConsumed(swigCPtr);
  }

}
