/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cmodules;

class mainJNI {
  public final static native void Entity_setStatut(long jarg1, int jarg2);
  public final static native int Entity_getStatut(long jarg1);
  public final static native void Entity_setPos(long jarg1, int jarg2, int jarg3);
  public final static native int Entity_getPosX(long jarg1);
  public final static native int Entity_getPosY(long jarg1);
  public final static native void set_Entity_posX(long jarg1, int jarg2);
  public final static native int get_Entity_posX(long jarg1);
  public final static native void set_Entity_posY(long jarg1, int jarg2);
  public final static native int get_Entity_posY(long jarg1);
  public final static native void set_Entity_statut(long jarg1, int jarg2);
  public final static native int get_Entity_statut(long jarg1);
  public final static native long new_Entity();
  public final static native void delete_Entity(long jarg1);
  public final static native long new_GlobalStatut();
  public final static native void set_GlobalStatut_Statut(long jarg1, int jarg2);
  public final static native int get_GlobalStatut_Statut(long jarg1);
  public final static native void GlobalStatut_askEnd(long jarg1);
  public final static native void set_GlobalStatut_endAsked(long jarg1, int jarg2);
  public final static native int get_GlobalStatut_endAsked(long jarg1);
  public final static native int GlobalStatut_endIsAsked(long jarg1);
  public final static native void GlobalStatut_dataUpdated(long jarg1);
  public final static native int GlobalStatut_isNewDataAvailable(long jarg1);
  public final static native void GlobalStatut_consumeData(long jarg1);
  public final static native int GlobalStatut_isDataConsumed(long jarg1);
  public final static native void delete_GlobalStatut(long jarg1);
  public final static native void startAll();
}
